# Generated by Django 4.2.4 on 2023-09-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_electeur_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='imagesPUB/')),
            ],
        ),
    ]
