# Generated by Django 4.2.4 on 2023-08-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0003_remove_utilisateur_account_and_more'),
        ('candidat', '0005_article_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id_proposition', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_proposition', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id_zone', models.AutoField(primary_key=True, serialize=False)),
                ('nom_zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id_Vote', models.AutoField(primary_key=True, serialize=False)),
                ('nature_vote', models.CharField(max_length=70)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.electeur')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.proposition')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Themes_cles',
            fields=[
                ('id_themes_cles', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_themes_cles', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.zone')),
            ],
        ),
        migrations.AddField(
            model_name='proposition',
            name='themes_cles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.themes_cles'),
        ),
    ]
