# Generated by Django 4.2.4 on 2023-08-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes_cles',
            name='zone',
        ),
        migrations.AddField(
            model_name='proposition',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.zone'),
        ),
    ]
