# Generated by Django 4.2.4 on 2023-08-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0005_article_date_creation'),
        ('MainApp', '0003_remove_utilisateur_account_and_more'),
        ('votes', '0002_remove_themes_cles_zone_proposition_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='themes_cles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.themes_cles'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='electeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.electeur'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.proposition'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.zone'),
        ),
    ]
