# Generated by Django 4.2.4 on 2023-08-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0012_ville_point'),
        ('votes', '0006_alter_zone_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='zone',
        ),
        migrations.AddField(
            model_name='proposition',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.ville'),
        ),
        migrations.AddField(
            model_name='vote',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.ville'),
        ),
    ]
