# Generated by Django 4.1.7 on 2023-08-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_proposition_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes_cles',
            name='zone',
        ),
    ]
