# Generated by Django 4.2.4 on 2023-08-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id_election', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_election', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_electoral',
            fields=[
                ('id_question_electoral', models.AutoField(primary_key=True, serialize=False)),
                ('intitule_question', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.election')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition_electoral',
            fields=[
                ('id_proposition_electoral', models.AutoField(primary_key=True, serialize=False)),
                ('reponse', models.CharField(max_length=100)),
                ('question_electoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.question_electoral')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id_candidat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=70)),
                ('surnom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('parti_politique', models.CharField(max_length=100)),
                ('biographie', models.CharField(max_length=255)),
                ('motivation', models.CharField(max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.election')),
            ],
        ),
    ]
