# Generated by Django 4.2.4 on 2023-08-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat')),
            ],
        ),
    ]
