# Generated by Django 4.1.7 on 2023-08-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='un contenu', max_length=400),
        ),
    ]
