# Generated by Django 4.1.7 on 2023-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0005_article_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id_Ville', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
    ]
