# Generated by Django 4.1.7 on 2023-08-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0006_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='localisation',
        ),
        migrations.AddField(
            model_name='candidat',
            name='Ville',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.ville'),
        ),
    ]
