# Generated by Django 4.1.7 on 2023-08-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0008_alter_candidat_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='motivation',
            field=models.CharField(max_length=254),
        ),
    ]
