# Generated by Django 4.1.7 on 2023-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0009_alter_candidat_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='motivation',
            field=models.CharField(max_length=255),
        ),
    ]
