# Generated by Django 4.1.7 on 2023-08-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0012_ville_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagesArt/'),
        ),
    ]
