# Generated by Django 4.1.7 on 2023-08-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0014_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.election'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='motivation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
